### ISSUE TITLE
ASLR handling on windows is not supported in rz_sys_aslr

### ISSUE THREAD

**Issue by gogo2464** [rizinorg/rizin#4147] opened 2024-01-24 10:12 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | windows 10
| File format of the file you reverse (mandatory)      | PE,
| Architecture/bits of the file (mandatory)            | x64
| `rizin -v` full output, **not truncated** (mandatory)  |rizin 0.7.0 @ windows-x86-64 commit: b2112ddcdf6be4fc292a699d0f77ed3add50d682

### Expected behavior

When I rerun the program, I would like to have the same base address for any function.

### Actual behavior

The base address of roblox change sometimes.

### Steps to reproduce the behavior

I did:

```
.\OUT\bin\rizin.exe -R "aslr=no" -e "pdb.autoload=true" -e scr.color=2 -c "dc" -e "search.in=analysis.fcn" -d C:\Users\yoshi\AppData\Local\Roblox\Versions\version-88cfc23f4e7d4e4b\RobloxPlayerBeta.exe
```

### Additional Logs, screenshots, source code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by XVilka** [comment] 2024-01-25 14:25
@gogo2464, please fill in the necessary information; the issue is invalid.

**Comment by gogo2464** [comment] 2024-01-26 10:22
@XVilka it is done

**Comment by gogo2464** [comment] 2024-01-29 10:35
@XVilka do you need more infos?

**Comment by wargio** [comment] 2024-02-09 13:46
ASLR handling is not implemented for windows in `rz_sys_aslr`

**Comment by wargio** [comment] 2024-02-09 14:22
According to windows manual you have to disable on the OS level and cannot be done via rz-run.

I would consider this as `won't fix`.

@XVilka

**Comment by gogo2464** [comment] 2024-02-09 14:58
Or we may just run the command:

`Get-Item -Path "C:\Program Files\Git\usr\bin\*.exe" | %{ Set-ProcessMitigation -Name $_.Name -Disable ForceRelocateImages }`

or recode it with the win32 api.

**Comment by wargio** [comment] 2024-02-11 16:22
So after extensive research on how windows ASLR works, i can confirm that is not possible to remove it programmatically.

**Closed as completed** 2024-02-12 04:22 UTC
Labels: enhancement, Windows, rz-run

**Comment by gogo2464** [comment] 2024-02-14 02:39
sure no problem. I need to try the newest PR merged. :) in the future we might replace it with windows api syscall.
