### ISSUE TITLE
Applying function signature swaps arguments with 'fastcall' cc.

### ISSUE THREAD

**Issue by LaylBongers** [rizinorg/rizin#3291] opened 2023-01-08 04:15 UTC
*Issue transferred from Cutter to Rizin by Megabeets*

---

**Environment information**
* Operating System: Windows 10, 64bit
* Cutter version: 2.1.2
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [x] Distribution repository
* File format: PE x86 binary (not 64-bit)

**Describe the bug**

When assigning a function signature on a `fastcall` calling convention function, the ECX and EDX arguments are swapped.

**To Reproduce**

1. Open up an executable that contains a fastcall function with 2 or more arguments. Note that in my test example, the function is using a total of 4 arguments.
![cutter_oTFSmsChzC](https://user-images.githubusercontent.com/3094382/211180038-e64e4d75-a087-4a34-a2b7-a9db46103c76.png)

2. Mark the function as using 'fastcall' calling convention, using the dropdown menu 
![cutter_BGyJX17YcJ](https://user-images.githubusercontent.com/3094382/211180029-0f81576a-5373-41df-bb60-8e4fc258a598.png)

3. Run `af` in command, and then refresh the disassembler view using F5, verifying that the two arguments have been detected. At this point they are in the correct order.
![cutter_YjRrkax2Ve](https://user-images.githubusercontent.com/3094382/211180101-647b7ff6-3401-4e4a-b060-44db6a253e77.png)

4. Apply a new function signature using `afs`. In this case I used `afs int32_t example_function(int32_t arg1, LPCSTR file_path, int32_t arg3, int32_t arg4);`
![cutter_SxW2y0sB6E](https://user-images.githubusercontent.com/3094382/211180132-f62e8999-83fe-4a39-ad66-d62f22fa3578.png)

5. After refreshing, the arguments are incorrectly flipped in the disassemble view.
![cutter_FbAV0nrXxu](https://user-images.githubusercontent.com/3094382/211180139-f1055b04-c2ec-4b5d-834e-4e6436991d36.png)

**Expected behavior**

Following fastcall, ECX and EDX should be assigned from left to right, thus, ECX should be argument 1, and EDX should be argument 2, as long as the parameters fit in registers.

**Additional context**

I have seen some similar behavior with cdecl, but was unable to quickly find reliable repro steps.

**Comment by LaylBongers** [comment] 2023-01-09 15:29
After testing, I've reproduced this issues using the following setups too:
- through cutter from latest available appveyor build
- through `rizin` CLI from the latest stable cutter release on windows
- through `rizin` CLI on ubuntu (run as WSL2)

**Comment by LaylBongers** [comment] 2023-01-09 16:08
*edited*
Correction on this additional data, I had mistyped a signature, and fixing that fixed that for this specific case, the other posts are still valid.

---

*edited again*
After checking with the correct signature, the results are still wrong:
![image](https://user-images.githubusercontent.com/3094382/211357340-b0b4c039-b375-4014-b94e-3c69cc7630f7.png)

Additionally, it's working correctly with x86_64 binaries.

**Comment by LaylBongers** [comment] 2023-01-09 18:15
This error also persists with 32-bit ELF binaries, and on windows the "x86: fastcall argument analysis" test appears to fail to be analyzed correctly:
![image](https://user-images.githubusercontent.com/3094382/211378501-7a60e7a0-3608-49f9-b185-8b5cd5032aae.png)

**Comment by LaylBongers** [comment] 2023-01-13 15:44
Tested on latest git build to verify. These steps still produce the same issue. At this time, `afva` correctly picks the right arguments in the right order, but cannot detect the two additional parameters given. Manually setting using `afs` still flips the first two parameters and, in fact, gets the stack positions wrong entirely (single byte offsets between them in the wrong location).
See here comparison between current git CI build, and ghidra (ghidra example includes additional data added in manually after, but the type sizes are the same):
![image](https://user-images.githubusercontent.com/3094382/212360084-4d8ef602-2c3c-480d-82a4-24cf5f41785a.png)
![image](https://user-images.githubusercontent.com/3094382/212360160-f98f2d34-c84e-41fa-8a97-622909633e13.png)

**Comment by ITAYC0HEN** [comment] 2023-01-14 08:55
Thank you for reporting these issue to us @LaylBongers! Appreciate it that you went the extra mile and performed several tests on both Cutter and Rizin.
Since the issue is most likely in the underlying core engine, which is Rizin, I transferred the issue from Cutter to Rizin.

Thank you very much!

**Closed as completed** 2023-01-15 12:40 UTC
Labels: rizin
