### ISSUE TITLE
grep regex

### ISSUE THREAD

**Issue by wargio** [rizinorg/rizin#64] opened 2020-11-02 13:43 UTC
Seems that the `~` (grep) command do not support properly regexes.

It would be nice to have a proper regex support to allow for example one of the following actions:

```bash
ii~\bsomeimport1234\b
```

the syntax could be the same as for the linux `grep` command or even better like the pcre one.

```bash
r2 -q -c 'ii' ipa://test.ipa | grep "\bsomeimport1234\b"
```

**Comment by ret2libc** [comment] 2021-08-10 16:00
@wargio I think the regex is now working well after your work. `~` does not support regex, but that's by design, let's say.... I'd close this issue!

**Closed as completed by ret2libc** 2021-08-10 16:00 UTC
Labels: enhancement, test-required
