### ISSUE TITLE
Failing `analysis_global_var` on v0.4.1 release

### ISSUE THREAD

**Issue by ghost** [rizinorg/rizin#2905] opened 2022-08-11 03:16 UTC
My environment: ArchLinux, x86_64, GCC 12.1.1 20220730

1. Get https://github.com/rizinorg/rizin/releases/download/v0.4.0/rizin-src-v0.4.0.tar.xz
2. Unpack it, and cd into rizin-v0.4.0
3. Get test/bins: make -C test/bins (I got 7d0c31ac7711de9c4d37f5047200dc5a407ff713)
4. Run: meson -Duse_sys_libzip=enabled build
   Note: with bundled libzip, build will fail with:
```
../subprojects/libzip-1.7.3/lib/zip_name_locate.c:65:41: error: ‘strcasecmp’ undeclared (first use in this function); did you mean ‘strncmp’?
```
5. Run test: cd build; ninja test
```
[...]
 91/103 rizin:integration / analysis_global_var                     FAIL            0.11s   exit status 1
>>> MALLOC_PERTURB_=45 /home/iyzsong/tmp/rizin-v0.4.0/build/test/integration/test_analysis_global_var
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
test_rz_analysis_global_var ERR
[XX] Fail at line 51: get global var by addr: expected to not be NULL but it was.

test_flag_confusion_space_name OK
test_flag_confusion_addr OK
test_flag_confusion_delete ERR
[XX] Fail at line 227: get global var by addr: expected to not be NULL but it was.

―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

 92/103 rizin:integration / bin                                     OK              0.03s
 93/103 rizin:integration / bin_vfiles                              OK              0.04s
 94/103 rizin:integration / autocmplt                               OK              0.31s
 95/103 rizin:integration / cpu_platform_profiles                   OK              0.16s
 96/103 rizin:integration / dwarf_info                              OK              0.02s
 97/103 rizin:integration / dwarf                                   OK              0.07s
 98/103 rizin:integration / open_analyse_save_load_project          OK              3.09s
 99/103 rizin:integration / pdb                                     OK              0.17s
100/103 rizin:integration / project_migrate                         OK              0.22s
101/103 rizin:integration / rzpipe                                  OK              0.10s
102/103 rizin:integration / dwarf_integration                       OK              3.70s
103/103 rizin:integration / sign_integration                        FAIL            0.14s   exit status 1
>>> MALLOC_PERTURB_=169 /home/iyzsong/tmp/rizin-v0.4.0/build/test/integration/test_sign_integration
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stdout:
test_analysis_sign_za_ppc ERR
[XX] Fail at line 59: vars count: expected 7, got 5.

test_analysis_sign_za_mips ERR
[XX] Fail at line 134: vars count: expected 17, got 13.

stderr:
WARNING: No calling convention defined for this file, analysis may be inaccurate.
WARNING: No calling convention defined for this file, analysis may be inaccurate.
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――


Summary of Failures:

 91/103 rizin:integration / analysis_global_var            FAIL            0.11s   exit status 1
103/103 rizin:integration / sign_integration               FAIL            0.14s   exit status 1

Ok:                 101
Expected Fail:      0
Fail:               2
Unexpected Pass:    0
Skipped:            0
Timeout:            0
```

**Comment by ret2libc** [comment] 2022-08-11 07:13
JFYI, we check all releases against all bundled dependencies, so it might happen for one reason or the other that when compiling against system libraries something breaks. I've seen few failures in Fedora package as well which I still need to investigate too.

**Comment by XVilka** [comment] 2022-08-13 12:55
I think we can ignore `sign_integration` since it will be removed in 0.5.0 (already removed in `dev`), but take the `analysis_global_var` seriously.

**Comment by XVilka** [comment] 2022-09-04 03:52
Broken signatures tests should be fixed by https://github.com/rizinorg/rizin/pull/3003

The global var analysis one looks like a genuine bug still.

@iyzsong can you reproduce the same issue with the latest "dev"?

**Comment by ghost** [comment] 2022-09-15 06:50
@XVilka Yes, with commit b13202b934, I get:
```
 90/113 rizin:unit / tokens                                         OK              0.06s
 91/113 rizin:unit / tree                                           OK              0.01s
 92/113 rizin:unit / type                                           OK              0.20s
 93/113 rizin:unit / uleb128                                        OK              0.01s
 94/113 rizin:unit / unum                                           OK              0.01s
 95/113 rizin:unit / util                                           OK              0.01s
 96/113 rizin:unit / vector                                         OK              0.01s
 97/113 rizin:unit / yank                                           OK              0.07s
 98/113 rizin:integration / analysis_global_var                     FAIL            0.09s   exit status 1
>>> MALLOC_PERTURB_=165 /home/iyzsong/pub/rizin/build/test/integration/test_analysis_global_var
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
test_rz_analysis_global_var ERR
[XX] Fail at line 51: get global var by addr: expected to not be NULL but it was.

test_flag_confusion_space_name OK
test_flag_confusion_addr OK
test_flag_confusion_delete ERR
[XX] Fail at line 227: get global var by addr: expected to not be NULL but it was.

 99/113 rizin:unit / threads                                        OK              2.01s
100/113 rizin:integration / analysis_il                             OK              0.06s
101/113 rizin:integration / autocmplt                               OK              0.41s
102/113 rizin:integration / basefind                                OK              0.21s
103/113 rizin:integration / bin                                     OK              0.03s
104/113 rizin:integration / bin_vfiles                              OK              0.04s
105/113 rizin:integration / cpu_platform_profiles                   OK              0.19s
106/113 rizin:integration / dwarf                                   OK              0.12s
107/113 rizin:integration / dwarf_info                              OK              0.02s
108/113 rizin:integration / analysis_graph                          OK              2.97s
109/113 rizin:integration / open_analyse_save_load_project          OK              3.53s
110/113 rizin:integration / pdb                                     OK              0.19s
111/113 rizin:integration / dwarf_integration                       OK              4.31s
112/113 rizin:integration / project_migrate                         OK              0.27s
113/113 rizin:integration / rzpipe                                  OK              0.07s

Summary of Failures:

 98/113 rizin:integration / analysis_global_var            FAIL            0.09s   exit status 1

Ok:                 112 
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

```

**Comment by ret2libc** [comment] 2023-01-17 15:08
Does it happen with current dev branch?

**Comment by XVilka** [comment] 2023-02-11 10:39
Moving to the next release due to the lack of answer

**Comment by ghost** [comment] 2023-02-16 06:04
> Does it happen with current dev branch?

Yes, 4 tests including analysis_global_var fails on commit 7f6f904 (testbins 0264ae4ee)
```
  9/116 rizin:unit / analysis_var                          FAIL            0.05s   exit status 1
 15/116 rizin:unit / bin_mach0                             FAIL            0.10s   exit status 1
101/116 rizin:integration / analysis_global_var            FAIL            0.13s   exit status 1
111/116 rizin:integration / dwarf_integration              FAIL            0.85s   exit status 1
```

Full testlog.txt: 
[testlog.txt](https://github.com/rizinorg/rizin/files/10752664/testlog.txt)

**Closed as completed** 2023-08-03 07:35 UTC
Labels: RzAnalysis, high-priority, waiting-for-author
