### ISSUE TITLE
Warn about or remove 256-byte limit for pf

### ISSUE THREAD

**Issue by imyxh** [rizinorg/rizin#3650] opened 2023-07-10 01:08 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Archlinux x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86_64
| `rizin -v` full output, **not truncated** (mandatory)  | rizinrizin 0.6.0 @ linux-x86-64

### Expected behavior

`pf [$N]$fmt` should warn me if `$N*sizeof($fmt) > 256`, or it should actually print all `$N` occurences.

### Actual behavior

Seems like there is a fixed-size buffer that makes zeroes show up after the first 256 bytes of an array from the `pf` command.

### Steps to reproduce the behavior
```
$ ./build/binrz/rizin/rizin /bin/ls
[0x00005f70]> pf [0x20+0x04]q @ 0x1000
0x00001000 = (qword)[ 0x657473696765725f, 0x656e6f6c434d5472, 0x5f5f00656c626154, 0x6174735f6362696c, 0x006e69616d5f7472, 0x69665f6178635f5f, 0x5f00657a696c616e, 0x6574615f6178635f, 0x6372747300746978, 0x617473626f00706d, 0x636f6c6c615f6b63, 0x5f64656c6961665f, 0x0072656c646e6168, 0x5f0074756f647473, 0x6f6c667265766f5f, 0x6574697277660077, 0x656b636f6c6e755f, 0x5f73747570660064, 0x64656b636f6c6e75, 0x746e6972705f5f00, 0x6261006b68635f66, 0x6c6c616d0074726f, 0x787461747300636f, 0x6b636174735f5f00, 0x6961665f6b68635f, 0x7063706d656d006c, 0x6e616c5f6c6e0079, 0x7473006f666e6967, 0x635f5f0072686372, 0x6c5f625f65707974, 0x656c72747300636f, 0x707974635f5f006e, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000 ]
[0x00005f70]> pf [0x20+0x04]q @ 0x1020
0x00001020 = (qword)[ 0x006e69616d5f7472, 0x69665f6178635f5f, 0x5f00657a696c616e, 0x6574615f6178635f, 0x6372747300746978, 0x617473626f00706d, 0x636f6c6c615f6b63, 0x5f64656c6961665f, 0x0072656c646e6168, 0x5f0074756f647473, 0x6f6c667265766f5f, 0x6574697277660077, 0x656b636f6c6e755f, 0x5f73747570660064, 0x64656b636f6c6e75, 0x746e6972705f5f00, 0x6261006b68635f66, 0x6c6c616d0074726f, 0x787461747300636f, 0x6b636174735f5f00, 0x6961665f6b68635f, 0x7063706d656d006c, 0x6e616c5f6c6e0079, 0x7473006f666e6967, 0x635f5f0072686372, 0x6c5f625f65707974, 0x656c72747300636f, 0x707974635f5f006e, 0x626d5f7465675f65, 0x78616d5f7275635f, 0x63776f7473626d00, 0x6972707773690073, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000 ]
```

Notice how there are four extra zeroes above that don't actually correspond to real data! This confused me for a long time as I thought the data I was looking at was actually zeroes, before I realized what was going on.

Also reproducible without `[]` just writing `pf qqqqqqqqq...`. r2 has same behavior fwiw.

**Comment by XVilka** [comment] 2023-07-10 02:31
I am slowly porting `pf` commands to the rzshell, will check if can be addressed there: https://github.com/rizinorg/rizin/pull/3467/files

Overall, the format code is horrible and should be rewritten from scratch. I isolated all relevant code into the one file: [`librz/type/format.c`](https://github.com/rizinorg/rizin/blob/dev/librz/type/format.c)

**Comment by XVilka** [comment] 2023-07-10 02:33
Just for the record, you can change the block size temporarily using `pf ... @!1024`

**Comment by imyxh** [comment] 2023-07-10 04:29
Ooh, that works for me. I had no idea that a general block size setting was a thing.

Perhaps it's worth adding a warning if the user tries to execute any command that will be truncated by the fixed block size?

**Comment by imyxh** [comment] 2023-07-10 04:31
If this applies to more than just `pf` we could change this issue to a general "Warn about truncation to block size` with label:enhancement

**Comment by XVilka** [comment] 2023-07-10 04:32
Also related issue: https://github.com/rizinorg/rizin/issues/317

**Comment by vmovupd** [comment] 2023-07-11 12:41
> If this applies to more than just `pf` we could change this issue to a general "Warn about truncation to block size` with label:enhancement

The same also applies to `pxj`. There will be junk or null bytes in the array after the first 256 bytes.

**Comment by ret2libc** [comment] 2023-07-24 08:46
> > If this applies to more than just `pf` we could change this issue to a general "Warn about truncation to block size` with label:enhancement
> 
> The same also applies to `pxj`. There will be junk or null bytes in the array after the first 256 bytes.

Could you provide an example of this? I couldn't reproduce.

**Comment by vmovupd** [comment] 2023-07-26 17:37
> > > If this applies to more than just `pf` we could change this issue to a general "Warn about truncation to block size` with label:enhancement
> > 
> > 
> > The same also applies to `pxj`. There will be junk or null bytes in the array after the first 256 bytes.
> 
> Could you provide an example of this? I couldn't reproduce.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 22H2 x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86 and x86_64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.5.2 @ windows-x86-64 commit: e2646b53b0f1aba8202f98b22d345ae73ad0e35f

### Steps to reproduce the behavior

```
[0x140013750]> px 272
- offset -    0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x140013750  4883 ec28 e8d3 0600 0048 83c4 28e9 6afe  H..(.....H..(.j.
0x140013760  ffff cccc 4883 ec28 4d8b 4138 488b ca49  ....H..(M.A8H..I
0x140013770  8bd1 e80d 0000 00b8 0100 0000 4883 c428  ............H..(
0x140013780  c3cc cccc 4053 458b 1848 8bda 4183 e3f8  ....@SE..H..A...
0x140013790  4c8b c941 f600 044c 8bd1 7413 418b 4008  L..A...L..t.A.@.
0x1400137a0  4d63 5004 f7d8 4c03 d148 63c8 4c23 d149  McP...L..Hc.L#.I
0x1400137b0  63c3 4a8b 1410 488b 4310 8b48 0848 8b43  c.J...H.C..H.H.C
0x1400137c0  08f6 4401 030f 740b 0fb6 4401 0383 e0f0  ..D...t...D.....
0x1400137d0  4c03 c84c 33ca 498b c95b e901 faff ffcc  L..L3.I..[......
0x1400137e0  488b c448 8958 0848 8968 1048 8970 1848  H..H.X.H.h.H.p.H
0x1400137f0  8978 2041 5648 83ec 2049 8b59 3848 8bf2  .x AVH.. I.Y8H..
0x140013800  4d8b f048 8be9 498b d148 8bce 498b f94c  M..H..I..H..I..L
0x140013810  8d43 04e8 6cff ffff 8b45 0424 66f6 d8b8  .C..l....E.$f...
0x140013820  0100 0000 451b c041 f7d8 4403 c044 8543  ....E..A..D..D.C
0x140013830  0474 114c 8bcf 4d8b c648 8bd6 488b cde8  .t.L..M..H..H...
0x140013840  740e 0000 488b 5c24 3048 8b6c 2438 488b  t...H.\$0H.l$8H.
0x140013850  7424 4048 8b7c 2448 4883 c420 415e c3cc  t$@H.|$HH.. A^..
[0x140013750]> pxj 272
[72,131,236,40,232,211,6,0,0,72,131,196,40,233,106,254,255,255,204,204,72,131,236,40,77,139,65,56,72,139,202,73,139,209,232,13,0,0,0,184,1,0,0,0,72,131,196,40,195,204,204,204,64,83,69,139,24,72,139,218,65,131,227,248,76,139,201,65,246,0,4,76,139,209,116,19,65,139,64,8,77,99,80,4,247,216,76,3,209,72,99,200,76,35,209,73,99,195,74,139,20,16,72,139,67,16,139,72,8,72,139,67,8,246,68,1,3,15,116,11,15,182,68,1,3,131,224,240,76,3,200,76,51,202,73,139,201,91,233,1,250,255,255,204,72,139,196,72,137,88,8,72,137,104,16,72,137,112,24,72,137,120,32,65,86,72,131,236,32,73,139,89,56,72,139,242,77,139,240,72,139,233,73,139,209,72,139,206,73,139,249,76,141,67,4,232,108,255,255,255,139,69,4,36,102,246,216,184,1,0,0,0,69,27,192,65,247,216,68,3,192,68,133,67,4,116,17,76,139,207,77,139,198,72,139,214,72,139,205,232,116,14,0,0,72,139,92,36,48,72,139,108,36,56,72,139,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
```

You can notice that there are null-bytes in `pxj` output after 256th byte, while in `px` output those are not null-bytes. If you decide to pick bigger size (~10 KB), then you see some junk bytes after a big block of null-bytes. The solution given by @XVilka fixes it.

**Comment by ret2libc** [comment] 2023-07-27 08:13
@XVilka the usual problem is that `core->block` is used instead of just reading from IO every time.

**Comment by XVilka** [comment] 2023-07-27 08:47
@ret2libc yes, and we have that all over the place: https://github.com/rizinorg/rizin/issues/2695

**Comment by XVilka** [comment] 2024-02-16 04:21
This particular issue is fixed. There are some `core->block` occurrences left in the printing-related code, but the size of the data chunk bigger than blocksize should be handled properly now. Closing in favor of a more generic issue: https://github.com/rizinorg/rizin/issues/2695

**Closed as completed by XVilka** 2024-02-16 04:21 UTC
Labels: pf
