### ISSUE TITLE
[FEAT REQ] When running analysis, time it

### ISSUE THREAD

**Issue by MCBEModder2020** [rizinorg/rizin#4693] opened 2024-10-29 23:51 UTC
**Is your feature request related to a problem? Please describe.**
i want to time how long it takes to open roblox

**Describe the solution you'd like**
while running analysis, display a live timer
after, output how long it took

**Describe alternatives you've considered**
none
making a pr for this myself but im trash at cpp

**Additional context**
this would be easy to implement probably

**Comment by Rot127** [comment] 2024-11-23 16:41
Duplicate of https://github.com/rizinorg/rizin/issues/4285

**Closed as not planned by Rot127** 2024-11-23 16:41 UTC
Labels: duplicate, enhancement, UX/UI
