### ISSUE TITLE
Meson failed TypeError not 'File'

### ISSUE THREAD

**Issue by dmknght** [rizinorg/rizin#2183] opened 2022-01-08 05:46 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | ParrotOS 5.0 amd64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.3

### Expected behavior
Meson generates files in `build` folder
### Actual behavior
Meson crashed with error log `TypeError: join() argument must be str, bytes, or os.PathLike object, not 'File'`
### Steps to reproduce the behavior
- Download release file of rizin, 0.3.3
- Run command `meson --buildtype=release build`
- Bug happens

### Additional Logs, screenshots, source code,  configuration dump, ...

Error log when run `meson build` only
```
The Meson build system
Version: 0.56.2
Source dir: /tmp/rizin
Build dir: /tmp/rizin/build
Build type: native build
Project name: rizin
Project version: v0.3.3
C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
C linker for the host machine: cc ld.bfd 2.35.2
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Program git found: YES (/usr/bin/git)
Message: rizin lib version: 0.3.3
Library dl found: YES
Run-time dependency threads found: YES
Library util found: YES
Library m found: YES
Compiler for C supports arguments --std=gnu99: YES 
Compiler for C supports arguments -Werror=sizeof-pointer-memaccess: YES 
Compiler for C supports arguments -fvisibility=hidden: YES 
Configuring config.h using configuration

|Executing subproject xxhash method meson 
|
|Project name: xxhash
|Project version: 0.6.5
|C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
|C linker for the host machine: cc ld.bfd 2.35.2
|Build targets in project: 1
|Subproject xxhash finished.

Dependency openssl skipped: feature use_sys_openssl disabled
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency libuv found: YES 1.40.0
Dependency tree-sitter skipped: feature use_sys_tree_sitter disabled

|Executing subproject tree-sitter method meson 
|
|Project name: tree-sitter
|Project version: undefined
|C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
|C linker for the host machine: cc ld.bfd 2.35.2
|Compiler for C supports arguments -std=gnu99: YES 
|Build targets in project: 2
|Subproject tree-sitter finished.

Message: HAVE_PTRACE: true
Message: USE_PTRACE_WRAP: true
Message: RZ_CHECKS_LEVEL: 1
Header <sys/personality.h> has symbol "ADDR_NO_RANDOMIZE" : YES 
Header <sys/procctl.h> has symbol "PROC_ASLR_CTL" : NO 
Checking for function "clock_gettime" : YES 
Library rt found: YES
Checking if "have extern char **environ" links: YES 
Message: HAVE_ENVIRON: true
Checking if "target is ios" links: NO 
Message: IS_IOS: false
Checking for function "arc4random_uniform" : NO 
Checking for function "explicit_bzero" : YES 
Checking for function "explicit_memset" : NO 
Checking for function "clock_nanosleep" : YES 
Checking for function "clock_gettime" with dependency -lrt: YES 
Checking for function "sigaction" : YES 
Checking for function "pipe" : YES 
Checking for function "execv" : YES 
Checking for function "execve" : YES 
Checking for function "execvp" : YES 
Checking for function "execl" : YES 
Checking for function "system" : YES 
Checking for function "fork" : YES 
Checking for function "nice" : YES 
Checking for function "copyfile" : NO 
Checking for function "strlcpy" : NO 
Checking for function "shm_open" with dependency -lrt: YES 
Checking for function "openpty" with dependency -lutil: YES 
Checking for function "forkpty" with dependency -lutil: YES 
Checking for function "login_tty" with dependency -lutil: YES 
Checking for function "pipe2" : YES 
Configuring rz_userconf.h using configuration
Message: Version Major: 00
Message: Version Minor: 30
Message: Version Patch: 30
Message: Version GitTip: 37b0f94c15435690bed2cfecebfd1eca045612a90
Configuring rz_version.h using configuration
Configuring librz.pc using configuration
Dependency zlib skipped: feature use_sys_zlib disabled

|Executing subproject zlib method meson 
|
|Project name: zlib
|Project version: 1.2.11
|C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
|C linker for the host machine: cc ld.bfd 2.35.2
|Compiler for C supports arguments -Wno-implicit-fallthrough: YES 
|Compiler for C supports arguments -Wno-implicit-function-declaration: YES 
|Build targets in project: 3
|Subproject zlib finished.


|Executing subproject sdb method meson 
|
|Project name: sdb
|Project version: undefined
|C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
|C linker for the host machine: cc ld.bfd 2.35.2
|Program python3 found: YES (/usr/bin/python3)
|Message: SDB version = 1.5.1-git
|Checking for function "getpid" : YES 
|Checking for function "_getpid" : NO 
|Configuring sdb_userconf.h using configuration
|Configuring sdb_version.h using configuration
|Build targets in project: 5
|Subproject sdb finished.

Dependency capstone skipped: feature use_sys_capstone disabled

|Executing subproject capstone-bundled method meson 
|
|Project name: capstone
|Project version: undefined
|C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
|C linker for the host machine: cc ld.bfd 2.35.2
|Build targets in project: 11
|Subproject capstone-bundled finished.

Program tree-sitter found: NO
Program node found: YES (/usr/bin/node)
Dependency liblz4 skipped: feature use_sys_lz4 disabled

|Executing subproject lz4 method meson 
|
|Project name: lz4
|Project version: 1.9.3
|C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
|C linker for the host machine: cc ld.bfd 2.35.2
|Build targets in project: 15
|Subproject lz4 finished.

Dependency libzip skipped: feature use_sys_libzip disabled

|Executing subproject libzip method meson 
|
|Project name: libzip
|Project version: 1.7.3
|C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
|C linker for the host machine: cc ld.bfd 2.35.2
|Program python3 found: YES (/usr/bin/python3)
|Dependency zlib from subproject subprojects/zlib-1.2.11 found: NO
|Found CMake: /usr/bin/cmake (3.22.1)
|Run-time dependency bzip2 found: NO (tried pkgconfig and cmake)
|Run-time dependency lzma found: NO (tried pkgconfig and cmake)
|Library lzma found: YES
|Checking for function "strcasecmp" : YES 
|Checking for function "arc4random" : NO 
|Checking for function "arc4random" : NO 
|Checking for function "clonefile" : NO 
|Checking for function "clonefile" : NO 
|Checking for function "explicit_bzero" : YES 
|Checking for function "explicit_memset" : NO 
|Checking for function "explicit_memset" : NO 
|Checking for function "fileno" : YES 
|Checking for function "fseeko" : YES 
|Checking for function "ftello" : YES 
|Checking for function "getprogname" : NO 
|Checking for function "getprogname" : NO 
|Checking for function "localtime_r" : YES 
|Checking for function "mkstemp" : YES 
|Checking for function "setmode" : NO 
|Checking for function "setmode" : NO 
|Checking for function "snprintf" : YES 
|Checking for function "strdup" : YES 
|Checking for function "stricmp" : NO 
|Checking for function "stricmp" : NO 
|Checking for function "strtoll" : YES 
|Checking for function "strtoull" : YES 
|Checking for function "_close" : NO 
|Checking for function "_close" : NO 
|Checking for function "_dup" : NO 
|Checking for function "_dup" : NO 
|Checking for function "_fdopen" : NO 
|Checking for function "_fdopen" : NO 
|Checking for function "_fileno" : NO 
|Checking for function "_fileno" : NO 
|Checking for function "_setmode" : NO 
|Checking for function "_setmode" : NO 
|Checking for function "_snprintf" : NO 
|Checking for function "_snprintf" : NO 
|Checking for function "_strdup" : NO 
|Checking for function "_strdup" : NO 
|Checking for function "_stricmp" : NO 
|Checking for function "_stricmp" : NO 
|Checking for function "_strtoi64" : NO 
|Checking for function "_strtoi64" : NO 
|Checking for function "_strtoui64" : NO 
|Checking for function "_strtoui64" : NO 
|Checking for function "_umask" : NO 
|Checking for function "_umask" : NO 
|Checking for function "_unlink" : NO 
|Checking for function "_unlink" : NO 
|Has header "stdbool.h" : YES 
|Has header "strings.h" : YES 
|Has header "unistd.h" : YES 
|Has header "dirent.h" : YES 
|Has header "fts.h" : YES 
|Has header "ndir.h" : NO 
|Has header "sys/dir.h" : YES 
|Has header "sys/ndir.h" : NO 
|Has header "sys/attr.h" : NO 
|Checking for size of "off_t" : 8
|Checking for size of "size_t" : 8
|Configuring config.h using configuration
|Has header "limits.h" : YES 
|Has header "inttypes.h" : YES 
|Checking for type "int8_t" : YES 
|Checking for type "uint8_t" : YES 
|Checking for type "int16_t" : YES 
|Checking for type "uint16_t" : YES 
|Checking for type "int32_t" : YES 
|Checking for type "uint32_t" : YES 
|Checking for type "int64_t" : YES 
|Checking for type "uint64_t" : YES 
|Checking for type "__int8" : NO 
|Checking for type "__int16" : NO 
|Checking for type "__int32" : NO 
|Checking for type "__int64" : NO 
|Configuring zipconf.h using configuration
|Build targets in project: 17
|Subproject libzip finished.

Dependency threads found: YES unknown (cached)

|Executing subproject mpc method meson 
|
|Project name: mpc
|Project version: d59264ae27228176f5b731871df1a87d7abbb5c8
|Build targets in project: 21
|Subproject mpc finished.


|Executing subproject yxml method meson 
|
|Project name: yxml
|Project version: 66507906673bc6159d5d620414479954c9c21c24
|C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
|C linker for the host machine: cc ld.bfd 2.35.2
|Build targets in project: 22
|Subproject yxml finished.

Message: Use bundled magic library

|Executing subproject tree-sitter-c method meson 
|
|Project name: tree-sitter-c
|Project version: f05e279aedde06a25801c3f2b2cc8ac17fac52ae
|Build targets in project: 38
|Subproject tree-sitter-c finished.

Configuring test_config.h using configuration
Compiler for C supports arguments -Wno-unused-result: YES 
Compiler for C supports arguments -Wno-unused-result: YES (cached)
Compiler for C supports arguments -Wno-unused-result: YES (cached)
Compiler for C supports arguments -Wno-unused-result: YES (cached)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 253, in run
    app.generate()
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 161, in generate
    self._generate(env)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 200, in _generate
    intr.run()
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 4715, in run
    super().run()
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 519, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 544, in evaluate_codeblock
    raise e
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 537, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 554, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 951, in method_call
    return obj.method_call(method_name, args, kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 56, in method_call
    return method(args, kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 228, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 2040, in add_dist_script_method
    script = self._find_source_script(args[0], script_args)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 1960, in _find_source_script
    found = dependencies.ExternalProgram(prog, search_dir=search_dir)
  File "/usr/lib/python3/dist-packages/mesonbuild/dependencies/base.py", line 1846, in __init__
    self.command = self._search(name, d)
  File "/usr/lib/python3/dist-packages/mesonbuild/dependencies/base.py", line 2049, in _search
    commands = self._search_dir(name, search_dir)
  File "/usr/lib/python3/dist-packages/mesonbuild/dependencies/base.py", line 1985, in _search_dir
    trial = os.path.join(search_dir, name)
  File "/usr/lib/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'File'
```

**Comment by ret2libc** [comment] 2022-01-08 14:05
This is caused by https://github.com/rizinorg/rizin/blob/v0.3.3/meson.build#L691 .
The fix is in https://github.com/rizinorg/rizin/commit/95106d3d9c768adb456e6cf6a17ebd8564e99643 .

**Comment by XVilka** [comment] 2022-01-10 16:17
Fixed in https://github.com/rizinorg/rizin/releases/tag/v0.3.4

**Closed as completed by XVilka** 2022-01-10 16:17 UTC
Labels: stable-backport
