### ISSUE TITLE
PE files with function names "section..text"

### ISSUE THREAD

**Issue by ITAYC0HEN** [rizinorg/rizin#45] opened 2020-10-20 12:32 UTC
**Description**
It is common to see a weird call to `section..text` in PE because there is a function in the same address.
```
$ rizin garbage_unpacked.exe

[0x00401473]> pd 1 @ 0x00401198
            0x00401198      call section..text

```

Example: [garbage_unpacked.zip](https://github.com/rizinorg/rizin/files/5413849/garbage_unpacked.zip)

**Comment by ITAYC0HEN** [comment] 2020-12-22 15:52
(edited with example)

**Comment by Maijin** [comment] 2021-01-03 15:01
(I can reproduce pre-aaa. After aaa this is a fcn.). I think it would be cool to keep it as a comment info for sections that aren't section..text as knowing that a malware is calling code from a start of section can be useful information.

**Comment by pelijah** [comment] 2021-03-28 21:36
Can't reproduce this on dev. I guess the bug was fixed by #449.

**Comment by p371jah** [comment] 2021-03-29 05:21
What is expected behavior? `call 0x00401000`?

**Comment by XVilka** [comment] 2021-03-29 05:29
@pelijah yes.

**Comment by XVilka** [comment] 2021-03-29 05:30
I think we should prohibit substitution of flags like `section.` or `segment.` in all kind of jumps and calls.

**Comment by ITAYC0HEN** [comment] 2021-03-30 12:07
> What is expected behavior? `call 0x00401000`?

For post-aaa Call fcn.0412345

Because it is already detected as a function, or should be detected as such

**Comment by ITAYC0HEN** [comment] 2021-03-30 12:09
For post-analysis I remember seeing similar stuff when asm.realname is enabled.

Or in other words, I saw it multiple times in cutter, after the default analysis and in which realnames are enabled (default)

**Comment by p371jah** [comment] 2021-03-30 17:38
> For post-aaa Call fcn.0412345
> 
> Because it is already detected as a function, or should be detected as such

But rizin shows `call fcn.00401000` after `aa`. What is wrong?

**Comment by ITAYC0HEN** [comment] 2021-03-30 20:39
Maybe you need to enable realnames.tonsee the issue? Sorry I don't have access to pc in the coming days, but I'm sure saw this times and times after analysis. Maybe a combination of realnames with something (I use cutter usually)

**Comment by p371jah** [comment] 2021-03-30 20:48
Confirm: `asm.flags.real=1` is enough

**Comment by p371jah** [comment] 2021-03-30 21:38
If function exists at destination offset it is enough to set `RZ_FLAGS_FS_FUNCTIONS` as preferable
```diff
diff --git a/librz/core/disasm.c b/librz/core/disasm.c
index ee2e0e51a..903c7874e 100644
--- a/librz/core/disasm.c
+++ b/librz/core/disasm.c
@@ -5014,7 +5014,7 @@ static bool set_jump_realname(RDisasmState *ds, ut64 addr, const char **kw, cons
                // nothing to do, neither demangled nor regular realnames should be shown
                return false;
        }
-       RzFlagItem *flag_sym = rz_flag_get_by_spaces(f, addr, RZ_FLAGS_FS_SYMBOLS, NULL);
+       RzFlagItem *flag_sym = rz_flag_get_by_spaces(f, addr, RZ_FLAGS_FS_FUNCTIONS, RZ_FLAGS_FS_SYMBOLS, NULL);
        if (!flag_sym || !flag_sym->realname) {
                // nothing to replace
                return false;
```
If there is no function flag at the given offset (function is not detected), you will still get `section..text`

**Closed** 2021-08-16 22:00 UTC
Labels: bug, test-required, high-priority
