### ISSUE TITLE
`dmh` command doesn't work properly

### ISSUE THREAD

**Issue by konatabrk** [rizinorg/rizin#678] opened 2021-02-21 19:35 UTC
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Archlinux x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.0-git @ linux-x86-64
commit: 0d5e708da4d836fa25245420abb8ca4804075332, build: 2021-02-21__18:42:02

### Expected behavior

Using `dmh` without arguments will print heap chunks inside of the heap segment

### Actual behavior

`dmh` prints `This address is not part of the arenas`. But there is only one arena - main_arena, so it should work to use the command without any additional argument.

 If I use these commands, then it works as expected:

```
:> dmha
main_arena @ 0x7f7fd3f7ca00
:> dmh @ 0x7f7fd3f7ca00

  Malloc chunk @ 0x55c7b6f50290 [size: 0x50][free]
  Malloc chunk @ 0x55c7b6f502e0 [size: 0x50][allocated]
  Malloc chunk @ 0x55c7b6f50330 [size: 0x50][allocated]
  Malloc chunk @ 0x55c7b6f50380 [size: 0x70][allocated]
  Malloc chunk @ 0x55c7b6f503f0 [size: 0x430][allocated]
  Malloc chunk @ 0x55c7b6f50820 [size: 0x30][allocated]
  Top chunk @ 0x55c7b6f50850 - [brk_start: 0x55c7b6f50000, brk_end: 0x55c7b6f71000]
```

### Steps to reproduce the behavior

Open any executable binary in `rizin`, then let the binary allocate several heap chunks and try to examine them by calling `dmh` without arguments

### Additional Logs, screenshots, source code,  configuration dump, ...

---

**Comment by fangxlmr** [comment] 2021-03-09 14:11
@Liyuanpei This issue is asigned to you as RSoC micro-task, so you could work on this from now on. Feel free to ask questions and send Pull Requests.

In case for anyone who is not aware about [RSoC](https://keenlab.tencent.com/zh/2021/03/04/RSoC-keenlab-2021/).

CC @XVilka

**Comment by Liyuanpei** [comment] 2021-03-14 11:16
[questions and something I gained from this issue-issues678-liyuanpei..pdf](https://github.com/rizinorg/rizin/files/6136543/questions.and.something.I.gained.from.this.issue-issues678-liyuanpei.pdf)

**Comment by fangxlmr** [comment] 2021-03-15 01:43
@Liyuanpei 

1. First of all, I don't think listing you questions in PDF is a proper way of doing this. You could just type those at comment in Markdown, so that everbody else knows what you're asking and probably try to help you out after a glance rather than download a pdf.
If you think the QA list and debug info is too long to display, then use [`<details>`](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) label nicely.

2. Relevant binaries will help to find the root cause. Check [this](https://github.com/rizinorg/rizin/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md) out.

**Comment by XVilka** [comment] 2021-03-15 03:43
Also for the testcases I recommend to provide both source and binaries, since the resulting binary could depend on the build environment a lot.

**Comment by XVilka** [comment] 2021-03-25 09:26
Issue is unassigned.

**Comment by ret2libc** [comment] 2021-03-26 08:13
Can we have a binary+libc to reproduce this bug? I cannot reproduce.

**Comment by konatabrk** [comment] 2021-03-28 13:25
What `libc` do you use to reproduce the issue?

**Comment by ret2libc** [comment] 2021-03-29 07:32
I'm on Fedora 33, x86-64, libc-2.32.so . What `libc` do you use to reproduce?

**Comment by konatabrk** [comment] 2021-04-01 20:03
I'm on Archlinux, x86-64, libc-2.33.so. But I don't think that there is much difference between 33 and 32 :thinking:

**Comment by ret2libc** [comment] 2021-04-02 07:38
Ok, I can reproduce on Archlinux. There's probably some subtle difference between our two libc versions :)

**Comment by wargio** [comment] 2021-04-29 11:51
This issue can be tested with the `/bins/elf/simple_malloc_x86_64`
```
[0x7f0a49fb9090]> dcu main 
Continue until 0x55687720070a using 1 bpsize
hit breakpoint at: 0x55687720070a
[0x55687720070a]> dmh
Arena @ 0x7f0a49c3ba00
Chunk(addr=0x556877812290, size=0x11c10, flags=PREV_INUSE)[allocated]
Chunk(addr=0x556877823ea0, size=0xf160, flags=PREV_INUSE)[top][brk_start: 0x556877812000, brk_end: 0x556877833000]

[0x55687720070a]> 7dso
hit breakpoint at: 0x556877200723
[0x556877200723]> dmh
Arena @ 0x7f0a49c3ba00
Chunk(addr=0x556877812290, size=0x11c10, flags=PREV_INUSE)[allocated]
Chunk(addr=0x556877823ea0, size=0x20, flags=PREV_INUSE)[allocated]
Chunk(addr=0x556877823ec0, size=0xf140, flags=PREV_INUSE)[top][brk_start: 0x556877812000, brk_end: 0x556877833000]

[0x556877200723]> dmha
main_arena @ 0x7f0a49c3ba00
[0x556877200723]> dmh @ 0x7f7fd3f7ca00
This address is not part of the arenas
[0x556877200723]> dmh 0x7f7fd3f7ca00
This address is not part of the arenas
```

**Comment by wargio** [comment] 2021-04-29 11:52
i think you do not need to use @ in this case, but it should be directly an argument for dmh

**Comment by MalhotraPulak** [comment] 2021-05-02 17:04
@ret2libc can you provide the binary and exact steps to reproduce it? I have set up an arch vm with glibc 2.33 but I am not able to reproduce the issue.

**Comment by ret2libc** [comment] 2021-05-03 07:55
> @ret2libc can you provide the binary and exact steps to reproduce it? I have set up an arch vm with glibc 2.33 but I am not able to reproduce the issue.

Mmmmm... I cannot reproduce anymore indeed. @merrychap are you able to?

**Comment by MalhotraPulak** [comment] 2021-07-09 10:34
Since this issue cannot be reproduced anymore and `dmh` has been refactored when it was moved to new shell I am closing this issue.

**Closed as completed by MalhotraPulak** 2021-07-09 10:34 UTC
Labels: bug, RzDebug, test-required, heap
